import { useEffect, useState } from 'react'
import { apiFetch } from '../../utils/api'

function Requests() {
  const [subjects, setSubjects] = useState([])
  const [form, setForm] = useState({ subjectId: '', type: 'attendance_correction', title: '', details: '' })
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  useEffect(() => { apiFetch('/student/request-subjects').then(setSubjects).catch((requestError) => setError(requestError.message)) }, [])
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(''); setMessage(''); try { const data = await apiFetch('/student/requests', { method: 'POST', body: JSON.stringify(form) }); setMessage(data.message); setForm({ subjectId: '', type: 'attendance_correction', title: '', details: '' }) } catch (requestError) { setError(requestError.message) } finally { setSaving(false) } }
  return <div><p className="text-sm font-semibold text-brand-600">SUPPORT</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-ink">Submit a Request</h1><p className="mt-2 text-sm text-muted">Send an academic, attendance, or extension request to the teacher assigned to your subject.</p>{message && <div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">{message}</div>}{error && <div className="mt-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}<form onSubmit={submit} className="mt-8 max-w-3xl rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="grid gap-5 sm:grid-cols-2"><label className="sm:col-span-2"><span className="text-sm font-semibold text-slate-700">Subject and teacher</span><select required value={form.subjectId} onChange={(event) => setForm({ ...form, subjectId: event.target.value })} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm outline-none focus:border-brand-500"><option value="">Choose subject</option>{subjects.map((subject) => <option key={subject.subjectId} value={subject.subjectId}>{subject.code} — {subject.name} · {subject.teacherName}</option>)}</select></label><label><span className="text-sm font-semibold text-slate-700">Request type</span><select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm outline-none focus:border-brand-500"><option value="attendance_correction">Attendance correction</option><option value="assignment_extension">Assignment extension</option><option value="academic">Academic request</option></select></label><label><span className="text-sm font-semibold text-slate-700">Title</span><input required maxLength="160" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm outline-none focus:border-brand-500" /></label><label className="sm:col-span-2"><span className="text-sm font-semibold text-slate-700">Details</span><textarea required maxLength="4000" rows="6" value={form.details} onChange={(event) => setForm({ ...form, details: event.target.value })} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm outline-none focus:border-brand-500" /></label><div className="flex justify-end sm:col-span-2"><button disabled={saving || !subjects.length} className="rounded-xl bg-brand-700 px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{saving ? 'Submitting…' : 'Submit request'}</button></div></div></form></div>
}
export default Requests
